### ISSUE TITLE
wrong data in "./training_data/SecStr/test.pkl"

### ISSUE THREAD

**Issue by LAJ-THU** [RSchmirler/data-repo_plm-finetune-eval#1]
When I was running the `Embedding_Generation_GPU.ipynb` notebook, I found that the test data provided in `./training_data/SecStr/test.pkl` had wrong arrangement as indicated by the screenshot, with columns corresponding to wrong type of data

<img width="897" alt="image" src="https://github.com/user-attachments/assets/27593e19-a9d9-45ac-ab10-f25f9cc85ddd"
![Xnip2024-08-15_20-37-53](https://github.com/user-attachments/assets/84b9d35d-6d81-492f-9c8f-5dcd606a9eff)

**Comment by RSchmirler** [comment]
Sorry for that, I just added the correct data. 
Something got mixed up there...
